export const CHANNELS_TOP_FETCH_STARTED = 'CHANNELS_TOP_FETCH_STARTED';
export const CHANNELS_TOP_FETCH_SC = 'CHANNELS_TOP_FETCH_SC';
export const CHANNELS_TOP_NEXT_SC = 'CHANNELS_TOP_NEXT_SC';
export const CHANNEL_FAVOURITE_TOOGLE = 'CHANNEL_FAVOURITE_TOOGLE';
export const CHANNEL_FAVOURITE_REMOVE = 'CHANNEL_FAVOURITE_REMOVE';
export const CHANNELS_TOP_SEARCH_CHANGED = 'CHANNELS_TOP_SEARCH_CHANGED';
export const CHANNELS_FAVOURITE_SEARCH_CHANGED = 'CHANNELS_FAVOURITE_SEARCH_CHANGED';